global:
  resolve_timeout: 5m
receivers:
- name: 'sysdig-test'
  webhook_configs:
    - url: 'https://webhook.site/' 
  slack_configs:
    - api_url: 'https://hooks.slack.com/services/' 
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'sysdig-test'
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: 'sysdig-test'
